### ISSUE TITLE
MOTD doesn't work

### ISSUE THREAD

**Issue by TiTo-418** [savethewools/Server#1]
<a href="http://imgur.com/jyJvWsh"><img src="http://i.imgur.com/jyJvWsh.png" title="source: imgur.com" /></a>

**Comment by TiTo-418** [comment]
@RubeVi

**Comment by RubeVi** [comment]
usa este formato en vez del "\u00A7" en vez del "&"

**Comment by TiTo-418** [comment]
ok, ahora intento

**Comment by RubeVi** [comment]
ya lo hice

**Comment by RubeVi** [comment]
1d9119999409a56fd3902b7fa11130d6384e734f

**Comment by TiTo-418** [comment]
@RubeVi Sigue :0

**Comment by RubeVi** [comment]
Arreglado
